name: Feature request
description: Suggest an idea for Ticker
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: "I'm always trying to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: checkboxes
    id: privacy
    attributes:
      label: Privacy
      options:
        - label: This feature keeps all data on-device (no network / telemetry)
          required: true
